apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications
  namespace: brokerlite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
      - name: notifications
        image: neena9940/brokerlite-notifications:latest
        envFrom:
        - configMapRef:
            name: brokerlite-config