import uuid
from pydantic import BaseModel

class OrderCreateRequest(BaseModel):
    ticker: str
    side: str                              # "BUY" / "SELL"
    quantity: int
    # generated by the CLIENT (frontend), not the server. This is the idempotency key:
    # retrying the same logical order reuses it; a new order gets a new one.
    client_token: uuid.UUID

class OrderResponse(BaseModel):
    id: uuid.UUID
    ticker: str
    side: str
    quantity: int
    price: float
    status: str

    model_config = {"from_attributes": True}   # build from SQLAlchemy objects directly

class HoldingResponse(BaseModel):
    ticker: str
    quantity: int
    avg_buy_price: float
    current_price: float
    market_value: float
    pnl: float            # (current_price - avg_buy_price) * quantity

class PortfolioResponse(BaseModel):
    holdings: list[HoldingResponse]
    total_value: float
    total_pnl: float